image: trion/ng-cli

cache:
  paths:
    - node_modules/
	- functions/node_modules/
before_script:
  - npm i -g firebase-tools
  - npm install -g @angular/cli
  
  # Deploy changes to the dev instance.
deploy staging to dev instance:
  stage: deploy
  script:
	- firebase use default
    - npm install
	- ng build
	- firebase deploy --only hosting
  only:
    refs:
	  - master
	changes:
	  - src/**/*

deploy functions to dev:
   stage: deploy
   script:
     - cd functions
	 - npm install
	 - cd ../
	 - firebase use default
	 - firebase deploy --only functions 
   only:
     refs:
	   - master
	 changes:
	   - functions/src/**/*
	   
deploy rules to dev:
  stage: deploy
  script:
    - firebase use default
	- firebase deploy --only firestore:rules
	- firebase deploy --only storage:rules
  only:
    refs:
	  - master
	changes:
	  - ./*.{rules}